<?php

namespace Sdz\RentCarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends EntityRepository
{
    public function myFindAll()
    {
        $query = $this->_em->createQuery('SELECT v FROM SdzRentCarBundle:Voiture v WHERE v.dispo = :dispo')->setParameter('dispo', 'oui');
        $resultats = $query->getResult();
        
        return $resultats;
    }
}
