<?php

namespace Sdz\RentCarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoitureLouerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureLouerRepository extends EntityRepository
{
    public function myFindAllLouer()
    {
   
    $query = $this->_em->createQuery('SELECT vl FROM SdzRentCarBundle:VoitureLouer vl');
    $resultats = $query->getResult();
        
     return $resultats;
    }
}
