parameters:
#    sdz_rent_car.example.class: Sdz\RentCarBundle\Example

services:
#    sdz_rent_car.example:
#        class: %sdz_rent_car.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
